name: Docker imgae creation for nodejs app
on: 
  workflow_call:
    # inputs:
    #     lambda_function_name:
    #     type: string
    #     required: true
    secrets:
        AWS_ACCESS_KEY_ID:
            required: true
        AWS_SECRET_ACCESS_KEY:
            required: true
        AWS_REGION:
             required: true

jobs: 
  build: 
    runs-on: ubuntu-latest
    environment: Development

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: nodejs/githubaction
      ECR_REGISTRY: 810471244058.dkr.ecr.eu-north-1.amazonaws.com

    steps: 
       - name: checkout code
         uses: actions/checkout@v3
   
       - name: configure aws credentials 
         uses: aws-actions/configure-aws-credentials@v3
         with: 
             aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
             aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
             aws-region: eu-north-1 ###${{secrets.AWS_REGION}}
       
       - name: login to ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
       

       - name: Build, Tag & Push Docker image to ECR
         run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latestv1 .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latestv1

             
       - name: Deploy to Lambda
         run: |
              aws lambda update-function-code --function-name nodejs_lambda_function --image-uri 810471244058.dkr.ecr.eu-north-1.amazonaws.com/nodejs/githubaction:latestv1
