name: Docker imgae creation for nodejs app
on: 
 push:
   branches: 
        - main 

jobs: 
  build: 
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps: 
       - name: checkout code
         uses: actions/checkout@v3
   
       - name: configure aws credentials 
         uses: aws-actions/configure-aws-credentials@v3
         with: 
             aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
             aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
             aws-region: ${{secrets.AWS_REGION}}
       
       - name: login to ECR
         run: |
              aws ecr get-login-password \
              | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
       - name : docker build
         run: docker build -t $ECR_REPOSITORY .

       - name: Tag & Push Docker image to ECR
         run: |
              docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
              docker push 810471244058.dkr.ecr.eu-north-1.amazonaws.com/nodejs/githubaction
        
        
      - name: Deploy to Lambda
        run: |
        aws lambda update-function-code --function-name nodejs_lambda_function --image-uri 810471244058.dkr.ecr.eu-north-1.amazonaws.com/nodejs/githubaction:latest

       # - name: docker build
       #   uses: docker/setup-buildx-action@v3
  
       # - name: setup docker login 
       #   uses: docker/login-action@v3
       #   with: 
       #       username: ${{secrets.DOCKER_USERNAME}}
       #       password: ${{secrets.DOCKER_PASSWORD}}
     
       # - name: build and push docker image  
       #   uses: docker/build-push-action@v5
       #   with: 
       #       context: .
       #       push: true
       #       tags: saurabhsonje/nodejs:latest
